team_abbreviations = {
    'Arizona Diamondbacks': 'ARI',
    'Atlanta Braves': 'ATL',
    'Baltimore Orioles': 'BAL',
    'Boston Red Sox': 'BOS',
    'Chicago Cubs': 'CHC',
    'Chicago White Sox': 'CHW',
    'Cincinnati Reds': 'CIN',
    'Cleveland Guardians': 'CLE',
    'Colorado Rockies': 'COL',
    'Detroit Tigers': 'DET',
    'Houston Astros': 'HOU',
    'Kansas City Royals': 'KC',
    'Los Angeles Angels': 'LAA',
    'Los Angeles Dodgers': 'LAD',
    'Miami Marlins': 'MIA',
    'Milwaukee Brewers': 'MIL',
    'Minnesota Twins': 'MIN',
    'New York Yankees': 'NYY',
    'New York Mets': 'NYM',
    'Oakland Athletics': 'OAK',
    'Philadelphia Phillies': 'PHI',
    'Pittsburgh Pirates': 'PIT',
    'San Diego Padres': 'SD',
    'San Francisco Giants': 'SF',
    'Seattle Mariners': 'SEA',
    'St. Louis Cardinals': 'STL',
    'Tampa Bay Rays': 'TB',
    'Texas Rangers': 'TEX',
    'Toronto Blue Jays': 'TOR',
    'Washington Nationals': 'WSH'
}

team_abbreviations_zh = {
    'Arizona Diamondbacks': '亞利桑那響尾蛇',
    'Atlanta Braves': '亞特蘭大勇士',
    'Baltimore Orioles': '巴爾的摩金鶯',
    'Boston Red Sox': '波士頓紅襪',
    'Chicago Cubs': '芝加哥小熊',
    'Chicago White Sox': '芝加哥白襪',
    'Cincinnati Reds': '辛辛那提紅人',
    'Cleveland Guardians': '克里夫蘭守護者',
    'Colorado Rockies': '科羅拉多洛磯',
    'Detroit Tigers': '底特律老虎',
    'Houston Astros': '休士頓太空人',
    'Kansas City Royals': '堪薩斯市皇家',
    'Los Angeles Angels': '洛杉磯天使',
    'Los Angeles Dodgers': '洛杉磯道奇',
    'Miami Marlins': '邁阿密馬林魚',
    'Milwaukee Brewers': '密爾瓦基釀酒人',
    'Minnesota Twins': '明尼蘇達雙城',
    'New York Yankees': '紐約洋基',
    'New York Mets': '紐約大都會',
    'Oakland Athletics': '奧克蘭運動家',
    'Philadelphia Phillies': '費城費城人',
    'Pittsburgh Pirates': '匹茲堡海盜',
    'San Diego Padres': '聖地牙哥教士',
    'San Francisco Giants': '舊金山巨人',
    'Seattle Mariners': '西雅圖水手',
    'St. Louis Cardinals': '聖路易紅雀',
    'Tampa Bay Rays': '坦帕灣光芒',
    'Texas Rangers': '德克薩斯遊騎兵',
    'Toronto Blue Jays': '多倫多藍鳥',
    'Washington Nationals': '華盛頓國民'
}